# 💳 SpendDNA

## Notebook 01: Dataset Exploration

---

### Purpose

This notebook performs a comprehensive exploration of the raw banking transaction dataset.

The objective is to understand the structure, quality, and characteristics of the dataset before any preprocessing begins.

**No modifications are made to the dataset in this notebook.**

---

### Input

`Datasets/raw/Dataset_Raw.csv`

### Output

`Data/raw_data.pkl`

### Dependencies

None

### Next Notebook

`02_Data_Cleaning.ipynb`

---

### Notebook Objectives

- Understand the dataset structure.
- Inspect column names and data types.
- Identify missing values.
- Detect duplicate records.
- Explore transaction descriptions.
- Examine date and amount formats.
- Identify potential data quality issues.
- Prepare observations for the data cleaning stage.

---

> **Note:** This notebook is strictly exploratory. The raw dataset must remain unchanged throughout this notebook.

In [1]:
# Import required libraries

from pathlib import Path

import pandas as pd
import numpy as np

In [2]:
# Configure project directories

PROJECT_ROOT = Path.cwd().parent

DATASET_DIR = PROJECT_ROOT / "Dataset"
DATA_DIR = PROJECT_ROOT / "Data"
OUTPUT_DIR = PROJECT_ROOT / "Outputs"
CONFIG_DIR = PROJECT_ROOT / "Config"

RAW_DATASET = DATASET_DIR / "raw" / "Dataset_Raw.csv"
RAW_DATA_PKL = DATA_DIR / "raw_data.pkl"

In [3]:
# Verify important project paths

print(f"Project Root : {PROJECT_ROOT}")
print(f"Dataset Path : {RAW_DATASET}")
print(f"Dataset Exists : {RAW_DATASET.exists()}")

Project Root : d:\Projects\SpendDNA
Dataset Path : d:\Projects\SpendDNA\Dataset\raw\Dataset_Raw.csv
Dataset Exists : True

In [4]:
# Load the transaction dataset

def load_dataset(path: Path) -> pd.DataFrame:
    """
    Load the raw transaction dataset.

    Parameters
    ----------
    path : Path
        Path to the CSV file.

    Returns
    -------
    pd.DataFrame
        Loaded transaction dataset.
    """

    return pd.read_csv(path)

In [5]:
# Read the dataset

df = load_dataset(RAW_DATASET)

print("Dataset loaded successfully.\n")
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Dataset loaded successfully.

Rows    : 1328
Columns : 8

In [6]:
# Display the first five records

display(df.head())

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962

## Explore Dataset Structure

In this section, we examine the overall structure of the dataset, including
its dimensions, column names, data types, memory usage, and basic statistics.
This helps us understand the dataset before performing any preprocessing.

In [7]:
# Display dataset dimensions

print("Dataset Shape")
print("-" * 40)
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Dataset Shape
----------------------------------------
Rows    : 1328
Columns : 8

In [8]:
# Display column names

print("Dataset Columns")
print("-" * 40)

for index, column in enumerate(df.columns, start=1):
    print(f"{index}. {column}")

Dataset Columns
----------------------------------------
1. Date
2. Time
3. Description
4. Type
5. Amount
6. Balance
7. Mode
8. Ref

In [9]:
# Display dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1328 entries, 0 to 1327
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         1328 non-null   str
 1   Time         1328 non-null   str
 2   Description  1328 non-null   str
 3   Type         1328 non-null   str
 4   Amount       1328 non-null   str
 5   Balance      1328 non-null   float64
 6   Mode         1328 non-null   str
 7   Ref          1328 non-null   str
dtypes: float64(1), str(7)
memory usage: 151.7 KB

In [10]:
# Display statistical summary

display(df.describe(include="all"))

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
count,1328,1328,1328,1328,1328,1328.000000,1328,1328
unique,617,832,283,3,1141,NaN,4,1307
top,2024-02-07,16:19,POS SWIGGY BANGALORE,DR,"Rs. 15,000",NaN,UPI,TXN829168
freq,6,6,30,670,5,NaN,1299,2
mean,NaN,NaN,NaN,NaN,NaN,147805.330572,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,341059.809969,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,-769127.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,-104585.750000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,151650.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,448324.250000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,720079.000000,NaN,NaN

## Data Quality Analysis

This section evaluates the quality of the dataset by identifying missing values,
duplicate records, duplicate transaction references, and the uniqueness of each
column. These observations will guide the data cleaning process in the next
notebook.

In [11]:
# Check missing values

missing_values = df.isnull().sum().to_frame(name="Missing Values")
missing_values["Percentage"] = (
    missing_values["Missing Values"] / len(df) * 100
).round(2)

display(missing_values)

             Missing Values  Percentage
Date                      0         0.0
Time                      0         0.0
Description               0         0.0
Type                      0         0.0
Amount                    0         0.0
Balance                   0         0.0
Mode                      0         0.0
Ref                       0         0.0

In [12]:
# Check duplicate rows

duplicate_rows = df.duplicated().sum()

print("Duplicate Rows")
print("-" * 40)
print(f"Total Duplicate Rows : {duplicate_rows}")

Duplicate Rows
----------------------------------------
Total Duplicate Rows : 18

In [13]:
# Check duplicate transaction references

duplicate_refs = df["Ref"].duplicated().sum()

print("Duplicate Transaction References")
print("-" * 40)
print(f"Duplicate References : {duplicate_refs}")

Duplicate Transaction References
----------------------------------------
Duplicate References : 21

In [14]:
# Display unique values in each column

unique_values = df.nunique().to_frame(name="Unique Values")

display(unique_values)

             Unique Values
Date                   617
Time                   832
Description            283
Type                     3
Amount                1141
Balance               1310
Mode                     4
Ref                   1307

## Key Findings

Based on the exploratory analysis, the following observations were made:

- The dataset contains transaction records with eight attributes.
- Multiple date formats are present within the `Date` column.
- The `Amount` column contains currency symbols and formatting, preventing it from being interpreted as a numeric field.
- The `Type` column contains inconsistent labels (such as `DR`, `CR`, and `Debit`).
- The `Balance` column is already stored as a numeric data type.
- Transaction descriptions appear in multiple formats and will require vendor normalization.
- Duplicate transaction references, if any, should be investigated during the data cleaning stage.
- These issues will be addressed in **Notebook 02: Data Cleaning**.

In [15]:
# Validate dataset before export

def validate_dataset(dataframe: pd.DataFrame) -> None:
    """
    Validate the loaded dataset before exporting.
    """

    print("Validation Summary")
    print("-" * 40)

    print(f"Rows                 : {dataframe.shape[0]}")
    print(f"Columns              : {dataframe.shape[1]}")
    print(f"Missing Values       : {dataframe.isnull().sum().sum()}")
    print(f"Duplicate Rows       : {dataframe.duplicated().sum()}")
    print(f"Duplicate References : {dataframe['Ref'].duplicated().sum()}")

    print("\nValidation Completed Successfully.")

In [16]:
# Execute validation

validate_dataset(df)

Validation Summary
----------------------------------------
Rows                 : 1328
Columns              : 8
Missing Values       : 0
Duplicate Rows       : 18
Duplicate References : 21

Validation Completed Successfully.

In [17]:
# Export raw dataset

df.to_pickle(RAW_DATA_PKL)

print("Dataset exported successfully.")
print(f"Export Location : {RAW_DATA_PKL}")

Dataset exported successfully.
Export Location : d:\Projects\SpendDNA\Data\raw_data.pkl

In [18]:
# Verify exported file

print("Export Verification")
print("-" * 40)

print(f"File Exists : {RAW_DATA_PKL.exists()}")
print(f"File Name   : {RAW_DATA_PKL.name}")

Export Verification
----------------------------------------
File Exists : True
File Name   : raw_data.pkl

In [19]:
# Notebook completion summary

print("=" * 60)
print("SpendDNA - Notebook 01 Completed")
print("=" * 60)

print(f"Input File        : {RAW_DATASET.name}")
print(f"Output File       : {RAW_DATA_PKL.name}")

print(f"Total Records     : {len(df):,}")
print(f"Total Features    : {df.shape[1]}")

print("\nNext Notebook")
print("--------------")
print("02_Data_Cleaning.ipynb")

print("\nStatus")
print("------")
print("Dataset exploration completed successfully.")
print("Raw dataset exported for the next stage.")

============================================================
SpendDNA - Notebook 01 Completed
============================================================
Input File        : Dataset_Raw.csv
Output File       : raw_data.pkl
Total Records     : 1,328
Total Features    : 8

Next Notebook
--------------
02_Data_Cleaning.ipynb

Status
------
Dataset exploration completed successfully.
Raw dataset exported for the next stage.

In [20]:
# Verify the exported dataset

loaded_df = pd.read_pickle(RAW_DATA_PKL)

print(f"Rows    : {loaded_df.shape[0]}")
print(f"Columns : {loaded_df.shape[1]}")

display(loaded_df.head())

Rows    : 1328
Columns : 8

,Date,Time,Description,Type,Amount,Balance,Mode,Ref
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,₹2462,678275.0,UPI,TXN190872
1,01-Jan-24,05:44,BHIM-BMTC,DR,50.00,681007.0,UPI,TXN143064
2,01-Jan-24,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,CR,₹84728,484728.0,NEFT,TXN246316
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,₹1828,-748745.0,UPI,TXN569226
4,01 Jan 2024,14:23,BHIM-BLINKIT,Debit,270.00,680737.0,UPI,TXN968962