# Function 6: Time-of-Day Spending Pattern Analysis

## Objective

This notebook analyzes transaction behaviour across different hours of the day.

### Goals

- Extract transaction hour
- Build hourly spending summary
- Create category vs hour spending matrix
- Identify peak spending hour
- Identify peak spending hour for each category
- Analyse late-night spending
- Generate metadata
- Export results for downstream functions

### Input

Data/monthly_trends.pkl

### Output

Data/time_of_day_patterns.pkl

In [1]:
# Project folders and file paths

from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

DATA_DIR = PROJECT_ROOT / "Data"
UTILS_DIR = PROJECT_ROOT / "Utils"

INPUT_FILE = DATA_DIR / "monthly_trends.pkl"
OUTPUT_FILE = DATA_DIR / "time_of_day_patterns.pkl"

In [2]:
# Import required libraries

import sys
import pickle
import pandas as pd
import numpy as np

sys.path.append(str(UTILS_DIR))

import time_of_day

In [3]:
# Load data from previous function

with open(INPUT_FILE, "rb") as file:
    monthly_data = pickle.load(file)
print("Monthly trends loaded successfully.")

Monthly trends loaded successfully.

In [4]:
# Extract transaction data

transactions = monthly_data["transactions"]
print("Transaction Shape :", transactions.shape)
display(transactions.head())

Transaction Shape : (1310, 10)

,Date,Time,Description,Transaction Type,Amount,Balance,Mode,Ref,Vendor,Category
0,2024-01-01,03:11,AMAZON SELLER SVCS,Debit,2462.0,678275.0,UPI,TXN190872,AMAZON,Uncategorized
1,2024-01-01,05:44,BHIM-BMTC,Debit,50.0,681007.0,UPI,TXN143064,BMTC,Uncategorized
2,2024-01-01,09:35,NEFT-TECHCRUSH LABS-SALARY MAY24,Credit,84728.0,484728.0,NEFT,TXN246316,TECHCRUSH LABS SALARY MAY,Uncategorized
3,2024-01-01,14:07,UPI-AMAN-8934@OKAXIS,Debit,1828.0,-748745.0,UPI,TXN569226,AMAN,Uncategorized
4,2024-01-01,14:23,BHIM-BLINKIT,Debit,270.0,680737.0,UPI,TXN968962,BLINKIT,Uncategorized

In [5]:
# Run time-of-day analysis

results = time_of_day.generate_time_of_day_patterns(
    transactions
)
print("Time-of-day analysis completed successfully.")

Time-of-day analysis completed successfully.

In [6]:
# Extract all outputs

hourly_summary = results["hourly_summary"]
category_hour_matrix = results["category_hour_matrix"]
category_peak_hours = results["category_peak_hours"]
late_night_summary = results["late_night_summary"]
peak_hour = results["peak_hour"]
metadata = results["metadata"]

In [7]:
# Display analysis results

print("=" * 70)
print("HOURLY SPENDING SUMMARY")
print("=" * 70)

display(hourly_summary)

print()

print("=" * 70)
print("CATEGORY VS HOUR MATRIX")
print("=" * 70)

display(category_hour_matrix)

print()

print("=" * 70)
print("CATEGORY PEAK HOURS")
print("=" * 70)

display(category_peak_hours)

print()

print("=" * 70)
print("OVERALL PEAK HOUR")
print("=" * 70)

print(peak_hour)

print()

print("=" * 70)
print("LATE NIGHT SUMMARY")
print("=" * 70)

print(late_night_summary)

======================================================================
HOURLY SPENDING SUMMARY
======================================================================

    Hour  Total Spend
0      0      37969.0
1      1      38882.0
2      2      20283.0
3      3      34868.0
4      4      43901.0
5      5      33671.0
6      6      55506.0
7      7      19938.0
8      8      41399.0
9      9      86701.0
10    10     140526.0
11    11     123389.0
12    12      77096.0
13    13     113819.0
14    14     121010.0
15    15      39647.0
16    16     100597.0
17    17      56604.0
18    18     101343.0
19    19      67848.0
20    20     138089.0
21    21      81545.0
22    22      55867.0
23    23      48403.0

======================================================================
CATEGORY VS HOUR MATRIX
======================================================================

Hour,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
Category,,,,,,,,,,,,,,,,,,,,,
Uncategorized,37969.0,38882.0,20283.0,34868.0,43901.0,33671.0,55506.0,19938.0,41399.0,86701.0,...,121010.0,39647.0,100597.0,56604.0,101343.0,67848.0,138089.0,81545.0,55867.0,48403.0

======================================================================
CATEGORY PEAK HOURS
======================================================================

               Peak Hour  Peak Spend
Category
Uncategorized         10    140526.0

======================================================================
OVERALL PEAK HOUR
======================================================================
{'Peak Hour': 10, 'Amount': 140526.0}

======================================================================
LATE NIGHT SUMMARY
======================================================================
{'Late Night Transactions': 219, 'Late Night Spend': np.float64(262666.0), 'Overall Spend': np.float64(1678901.0), 'Percentage': np.float64(15.645115465414577)}

In [8]:
# Display hourly spending chart

print("=" * 70)
print("HOURLY SPENDING VISUALIZATION")
print("=" * 70)

time_of_day.print_hourly_bars(
    hourly_summary
)

======================================================================
HOURLY SPENDING VISUALIZATION
======================================================================
00 | ████████
01 | ████████
02 | ████
03 | ███████
04 | █████████
05 | ███████
06 | ███████████
07 | ████
08 | ████████
09 | ██████████████████
10 | ██████████████████████████████
11 | ██████████████████████████
12 | ████████████████
13 | ████████████████████████
14 | █████████████████████████
15 | ████████
16 | █████████████████████
17 | ████████████
18 | █████████████████████
19 | ██████████████
20 | █████████████████████████████
21 | █████████████████
22 | ███████████
23 | ██████████

In [9]:
# Validate generated outputs

assert len(hourly_summary) == 24
assert category_hour_matrix.shape[1] == 24
assert "Peak Hour" in peak_hour
assert metadata["total_hours"] == 24
print("Validation completed successfully.")

Validation completed successfully.

In [10]:
# Save results for next function

time_of_day_data = {
    "transactions": transactions,
    "hourly_summary": hourly_summary,
    "category_hour_matrix": category_hour_matrix,
    "category_peak_hours": category_peak_hours,
    "late_night_summary": late_night_summary,
    "peak_hour": peak_hour,
    "metadata": metadata
}

with open(OUTPUT_FILE, "wb") as file:
    pickle.dump(time_of_day_data, file)

print("Time-of-day patterns exported successfully.")

Time-of-day patterns exported successfully.

In [11]:
# Print final summary

print("=" * 70)
print("FUNCTION 6 SUMMARY")
print("=" * 70)

print(f"Transactions          : {metadata['total_transactions']}")
print(f"Categories            : {metadata['total_categories']}")
print(f"Hours Analysed        : {metadata['total_hours']}")

print()
print("Peak Spending Hour")
print(peak_hour)
print()
print("Late Night Summary")
print(late_night_summary)
print()
print("Function 6 completed successfully.")

======================================================================
FUNCTION 6 SUMMARY
======================================================================
Transactions          : 1304
Categories            : 1
Hours Analysed        : 24

Peak Spending Hour
{'Peak Hour': 10, 'Amount': 140526.0}

Late Night Summary
{'Late Night Transactions': 219, 'Late Night Spend': np.float64(262666.0), 'Overall Spend': np.float64(1678901.0), 'Percentage': np.float64(15.645115465414577)}

Function 6 completed successfully.

In [12]:
# Validate outputs

print("=" * 70)
print("VALIDATION")
print("=" * 70)

assert len(hourly_summary) == 24
assert category_hour_matrix.shape[1] == 24
assert metadata["total_hours"] == 24

print("Rows in Hourly Summary :", len(hourly_summary))
print("Hours Covered          :", metadata["total_hours"])
print("Peak Hour              :", peak_hour["Peak Hour"])
print("Validation completed successfully.")

======================================================================
VALIDATION
======================================================================
Rows in Hourly Summary : 24
Hours Covered          : 24
Peak Hour              : 10
Validation completed successfully.

In [13]:
# Export results

time_of_day_data = {
    "transactions": transactions,
    "hourly_summary": hourly_summary,
    "category_hour_matrix": category_hour_matrix,
    "category_peak_hours": category_peak_hours,
    "late_night_summary": late_night_summary,
    "peak_hour": peak_hour,
    "metadata": metadata
}

with open(OUTPUT_FILE, "wb") as file:
    pickle.dump(time_of_day_data, file)

print("Time-of-day patterns exported successfully.")

Time-of-day patterns exported successfully.

In [14]:
# Print summary

print("=" * 70)
print("FUNCTION 6 SUMMARY")
print("=" * 70)

print(f"Transactions : {metadata['total_transactions']}")
print(f"Categories   : {metadata['total_categories']}")
print(f"Hours        : {metadata['total_hours']}")

print()
print("Peak Hour")
print(peak_hour)

print()
print("Late Night Summary")
print(late_night_summary)

print()
print("Function 6 completed successfully.")

======================================================================
FUNCTION 6 SUMMARY
======================================================================
Transactions : 1304
Categories   : 1
Hours        : 24

Peak Hour
{'Peak Hour': 10, 'Amount': 140526.0}

Late Night Summary
{'Late Night Transactions': 219, 'Late Night Spend': np.float64(262666.0), 'Overall Spend': np.float64(1678901.0), 'Percentage': np.float64(15.645115465414577)}

Function 6 completed successfully.